heat_template_version: 2017-02-24
description: Ubuntu 16 + bank

parameters:
  bank_id:
    type: string
    description: Instance name
  zoo_ip:
    type: string
    description: Instance name
  server_net_name:
    type: string
    description: Name of the private network
  zoo_net_name:
    type: string
    description: Name of the zookeeper subnetwork
  server_snet_name:
    type: string
    description: Name of the server subnetwork
  zoo_snet_name:
    type: string
    description: Name of the zookeeper subnetwork
  keypair_name:
    type: string
    description: Name of the keypair for the server

resources:
  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: keypair_name }
      save_private_key: true 
  public_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: server_net_name }
      fixed_ips:
      - subnet_id: { get_param: server_snet_name }
        ip_address: 
          str_replace:
            template: 10.1.2.10%bank_id%
            params:
              "%bank_id%": { get_param: bank_id }
  private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: zoo_net_name }
      fixed_ips:
      - subnet_id: { get_param: zoo_snet_name }
  floating_ip: 
    type: OS::Neutron::FloatingIP 
    properties: 
      floating_network_id: ExtNet 
      port_id: { get_resource: public_port }
  vm1:
    type: OS::Nova::Server
    properties:
      name: 
        str_replace:
          template: bank%bank_id%
          params:
            "%bank_id%": { get_param: bank_id } 
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      key_name: { get_resource: keypair }
      networks:
        - port: { get_resource: public_port }
        - port: { get_resource: private_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            resolv_conf:
              nameservers:
                - 8.8.8.8
                - 8.8.4.4
            # Update apt database on first boot
            apt_update: true
            # Install packages
            packages:
              - default-jre
            write_files:
              - path: /run/installBank.sh
                permissions: 0755
                content: |
                  #!/bin/bash
                  mkdir -p /opt/bank
                  cd /opt/bank
                  wget https://github.com/Thunkar/cnvr/raw/master/Bank.jar
            runcmd:
              - [ bash, -x, /run/installBank.sh ]
#              - [ java, -jar, /opt/bank/Bank.jar, %zoo_ip%, 80, -Djava.net.preferIPv4Stack=true ]
          params:
            "%zoo_ip%" : { get_param: zoo_ip }
outputs:
  vm_IP:
    description: Floating IP assigned to the VM 
    value: { get_attr: [floating_ip, floating_ip_address] }
  public_key:
    description: The public key of the keypair.
    value: { get_attr: [keypair, public_key] }
  private_key:
    description: The private key of the keypair.
    value: { get_attr: [keypair, private_key] }