heat_template_version: 2017-02-24
description: Ubuntu 16 + zookeeper

parameters:
  zoo_id:
    type: string
    description: Instance name
  zoo_net_name:
    type: string
    description: Name of the private network
  zoo_snet_name:
    type: string
    description: Name of the private subnetwork
  keypair_name:
    type: string
    description: Name of the keypair for the server

resources: 
  keypair:
    type: OS::Nova::KeyPair
    properties:
      name: { get_param: keypair_name }
      save_private_key: true
  private_port:
    type: OS::Neutron::Port
    properties:
      network_id: { get_param: zoo_net_name }
      fixed_ips:
      - subnet_id: { get_param: zoo_snet_name }
        ip_address: 
          str_replace:
            template: 10.1.1.10%zoo_id%
            params:
              "%zoo_id%": { get_param: zoo_id }
  vm1:
    type: OS::Nova::Server
    properties:
      name: 
        str_replace:
          template: zoo%zoo_id%
          params:
            "%zoo_id%": { get_param: zoo_id } 
      image: xenial-server-cloudimg-amd64-vnx
      flavor: m1.smaller
      key_name: { get_resource: keypair }
      networks:
        - port: { get_resource: private_port }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #cloud-config
            resolv_conf:
              nameservers:
                - 8.8.8.8
                - 8.8.4.4
            # Update apt database on first boot
            apt_update: true
            # Install packages
            packages:
              - default-jre
            write_files:
              - path: /run/installZooKeeper.sh
                permissions: 0755
                content: |
                  #!/bin/bash
                  adduser --disabled-password --gecos "" hadoop
                  mkdir -p /data/zookeeper
                  chown -R hadoop:hadoop /data
                  cd /opt
                  wget http://apache.is.co.za/zookeeper/zookeeper-3.4.10/zookeeper-3.4.10.tar.gz
                  tar -xvf zookeeper-3.4.10.tar.gz
                  chown hadoop:hadoop -R zookeeper-3.4.10
                  su hadoop
                  bash -c "cat > /opt/zookeeper-3.4.10/conf/zoo.cfg <<EOL
                  tickTime=2000
                  dataDir=/data/zookeeper
                  clientPort=2181
                  initLimit=10
                  syncLimit=5
                  server.1=10.1.1.101:2888:3888
                  server.2=10.1.1.102:2888:3888
                  EOL"
                  bash -c "echo %zoo_id% >> /data/zookeeper/myid"
            runcmd:
              - [ bash, -x, /run/installZooKeeper.sh ]
              - [ bash, -x, /opt/zookeeper-3.4.10/bin/zkServer.sh, start ]
          params:
            "%zoo_id%" : { get_param: zoo_id }

outputs:
  public_key:
    description: The public key of the keypair.
    value: { get_attr: [keypair, public_key] }
  private_key:
    description: The private key of the keypair.
    value: { get_attr: [keypair, private_key] }